service: portfolio
image: npezza/portfolio

servers:
  - 5.161.249.108

env:
  secret:
    - GIT_URL

registry:
  username: npezza
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

proxy:
  host: pezza.co
