service: portfolio
retain_containers: 1

servers:
  web:
    hosts:
      - homelab.pezza.co

env:
  secret:
    - GIT_URL

registry:
  server: localhost:5555

builder:
  arch: amd64

proxy:
  ssl: true
  host: pezza.co
  forward_headers: true

ssh:
  user: nick
  proxy: cloudflared access ssh --hostname %h
