service: portfolio
image: npezza/portfolio

servers:
  - 5.161.249.108

env:
  secret:
    - GIT_URL

registry:
  server: "localhost:5555"

builder:
  arch: amd64

proxy:
  ssl: true
  host: pezza.co
  forward_headers: true
