service: portfolio
retain_containers: 1

servers:
  web:
    hosts:
      - 100.72.208.91

env:
  secret:
    - GIT_URL

registry:
  server: localhost:5555

builder:
  arch: amd64

proxy:
  ssl: false
  host: pezza.co
  forward_headers: true
