service: portfolio
image: npezza/portfolio

servers:
  - 192.168.4.216

env:
  secret:
    - GIT_URL

registry:
  server: "localhost:5555"

builder:
  arch: amd64

proxy:
  ssl: true
  host: pezza.co
  forward_headers: true

ssh:
  user: nick
  port: 22
